# GitHub Pages Configuration for Kienyeji Farm Website

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
title: "Kienyeji Farm - Fresh Free-Range Chicken"
description: "Order fresh, free-range Kienyeji chicken in Kenya. Naturally raised, farm to table indigenous chicken with rich flavor and unbeatable nutrition."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # will be automatically set by GitHub Pages

# SEO and social
lang: en_US
author: "Kienyeji Farm"
twitter:
  username: 
  card: summary_large_image

# Include/exclude files
include:
  - _pages
exclude:
  - README.md
  - .gitignore
  - vendor
  - node_modules

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass settings
sass:
  style: compressed

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/og-image.jpg